domain: staticfilesimporter.github.io
url: https://staticfilesimporter.github.io
baseurl: "/test"

title: Wind
email: wind@example.com
author: Wind Sample

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
